export default [
    {
        name:'容器组件',
        children:[
            {
                name:'多列容器',
                tag:'el-row',
                width:'100%',
                paddingLeft:0,
                paddingRight:0,
                paddingTop:0,
                paddingBottom:0,
                marginLeft:0,
                marginRight:0,
                marginTop:0,
                marginBottom:0,
                col:1,
                spans:[24],
                children:[]
            },
            // {
            //     name:'单列容器',
            //     tag:'single-container',
            //     width:'100%',
            //     paddingLeft:0,
            //     paddingRight:0,
            //     paddingTop:0,
            //     paddingBottom:0,
            //     marginLeft:0,
            //     marginRight:0,
            //     marginTop:0,
            //     marginBottom:0,
            //     radius:0,
            //     minHeight:'100px',
            //     height:'auto',
            //     background:'#409eff',
            //     children:[]
            // },
            // {
            //     name:'flex多列容器',
            //     tag:'multiple-container',
            //     width:'100%',
            //     paddingLeft:0,
            //     paddingRight:0,
            //     paddingTop:0,
            //     paddingBottom:0,
            //     marginLeft:0,
            //     marginRight:0,
            //     marginTop:0,
            //     marginBottom:0,
            //     radius:0,
            //     minHeight:'100px',
            //     height:'auto',
            //     background:'#409eff',
            //     align:'space-start',
            //     children:[]
            // }
        ]
    },
    {
        name:'表单组件',
        children:[
            {
                name:"表单项",
                tag:"label",
                label:'输入框',
                labelColor:'#121212',
                labelSize:'16px',
                width:'100%',
                height: "40px",
                inputWidth:'calc(100% - 100px)',
                paddingLeft:"0px",
                paddingRight:"0px",
                paddingTop:"0px",
                paddingBottom:"0px",
                marginLeft:"0px",
                marginRight:"0px",
                marginTop:"0px",
                marginBottom:"0px",
                children: []
            },
            {
                name:'输入框',
                tag:'input',
                type:'text',
                attr:'form.input',
                placeholder:'请输入',
                label:'输入框',
                labelColor:'#121212',
                labelSize:'16px',
                width:'100%',
                height: "40px",
                labelWidth:'80px',
                inputWidth:'calc(100% - 100px)',
                paddingLeft:"0px",
                paddingRight:"0px",
                paddingTop:"0px",
                paddingBottom:"0px",
                marginLeft:"0px",
                marginRight:"0px",
                marginTop:"0px",
                marginBottom:"0px",
                maxlength:'',
                prefixIcon:'',
                suffixIcon:'',
                size:'medium',
                rows:2,
                disabled:false,
                clearable:true,
                readonly:false,
                showWordLimit:false
            },
            {
                name:"选择器",
                tag:"select",
                attr:'form.select',
                placeholder:'请选择',
                label:'选择器',
                labelColor:'#121212',
                labelSize:'16px',
                width:'100%',
                height: "40px",
                labelWidth:'80px',
                inputWidth:'calc(100% - 100px)',
                paddingLeft:"0px",
                paddingRight:"0px",
                paddingTop:"0px",
                paddingBottom:"0px",
                marginLeft:"0px",
                marginRight:"0px",
                marginTop:"0px",
                marginBottom:"0px",
                options:[
                    {label:'选项1',value:1},
                    {label:'选项2',value:2},
                    {label:'选项3',value:3},
                ],
                value:1,
                size: 'medium',
                disabled:false,
                clearable:true,
                readonly:false,
                filterable: false,
                multiple: false
            },
            {
                name:"单选框",
                tag:"radio",
                options:[
                    {label:'选项1',value:1},
                    {label:'选项2',value:2},
                    {label:'选项3',value:3},
                ],
                placeholder:'请选择',
                value:1,
                disabled:false,
                size: 'medium',
                border: false
            },
            {
                name:"多选框",
                tag:"checkbox",
                options:[
                    {label:'选项1',value:1},
                    {label:'选项2',value:2},
                    {label:'选项3',value:3},
                ],
                placeholder:'请选择',
                value:1,
                disabled:false,
                size: 'medium',
                border: false
            },
            {
                name:"级联选择",
                tag:"cascader",
                options:[
                    {label:'选项1',value:1},
                    {label:'选项2',value:2},
                    {label:'选项3',value:3},
                ],
                placeholder:'请选择',
                value:1,
                disabled:false,
                size: 'medium',
                border: false
            },
            {
                name:"时间组件",
                tag:"date",
                attr:'form.date',
                label: '日期选择',
                type:'date',
                placeholder:'请选择',
                value:1,
                labelColor:'#121212',
                labelSize:'16px',
                width:'100%',
                height: "40px",
                labelWidth:'80px',
                inputWidth:'calc(100% - 100px)',
                paddingLeft:0,
                paddingRight:0,
                paddingTop:0,
                paddingBottom:0,
                marginLeft:0,
                marginRight:0,
                marginTop:0,
                marginBottom:0,
                size: 'medium',
                disabled:false,
                clearable:true,
                readonly:false,
            },
            {
                name:"评分",
                tag:"rate",
                value:1,
                disabled:false,
                max:5
            },
            {
                name:"滑块",
                tag:"slider",
                value:1,
                disabled:false
            },
            {
                name:"图片上传",
                tag:"upload",
                attr:'form.upload',
                value:1,
                width: '200px',
                height: '200px',
                paddingLeft:"0px",
                paddingRight:"0px",
                paddingTop:"0px",
                paddingBottom:"0px",
                marginLeft:"0px",
                marginRight:"0px",
                marginTop:"0px",
                marginBottom:"0px",
                radius:'6px',
                disabled:false
            },
            {
                name:"颜色选择器",
                tag:"color",
                value:1,
                disabled:false
            },
            {
                name:"开关",
                tag:"switch",
                value:1,
                disabled:false
            },
            {
                name:"计数器",
                tag:"input-number",
                value:1,
                disabled:false
            }
        ]
    },
    {
        name:'基础组件',
        children:[
            {
                name:'按钮',
                tag:'button',
                text:'按钮',
                type:'primary',
                size:'medium',
                plain:false,
                round:false,
                circle:false,
                disabled:false
            },
            {
                name:'图标',
                tag:'icon',
                icon:'el-icon-edit',
                size:'medium',
                disabled:false
            },
            {
                name:'结果',
                tag:'result',
                icon:'el-icon-edit',
                size:'medium',
                disabled:false
            },
            {
                name:'标签',
                tag:'tag',
                icon:'el-icon-edit',
                size:'medium',
                disabled:false
            },
            {
                name:'头像',
                tag:'avatar',
                icon:'el-icon-edit',
                size:'medium',
                disabled:false
            },
            {
                name:'步骤条',
                tag:'step',
                icon:'el-icon-edit',
                size:'medium',
                disabled:false
            },
            {
                name: '时间线',
                tag: 'timeline',
                icon: 'el-icon-edit',
                size: 'medium',
                disabled: false
            }
        ]
    },
]